version: '2'
services:
    web:
      build: . 
      ports: 
          - 8080:8080
      stdin_open: true
      tty: true
      depends_on:
          - db
    db:
        container_name: sample_db
        image: postgres:latest
        volumes:
            - sample_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=mlp
            - POSTGRES_USER=plm
            - POSTGRES_DB=plm
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 15432:5432

volumes:
    sample_db: {}
